select * from customer;
---Q1.what is the total revenue generated by male vs female?
select sum(purchase_amount),gender from customer
 group by gender;
---Q2.which customer use discount and still spent more than average amount
select customer_id ,purchase_amount from customer
 where discount_applied='Yes' and
 purchase_amount>=(select avg(purchase_amount) from customer)
--Q3.which are the top 5 products with highest review rating?
select item_purchased,avg(review_rating) as "avg review_rating" from customer
 group by item_purchased
 order by avg(review_rating)
 desc limit 5;
--Q4.compare average purchase amount between the standard and Express?
select avg(purchase_amount) as "avg_purchase_amount",shipping_type from customer
 where shipping_type in ('Express','Standard')
 group by shipping_type;
---Q5.Do subscribed customers spend more?compare average spend and total revenue by subscribed and un subcribed?
select round(avg(purchase_amount),2) as "avg_spend",round(sum(purchase_amount),2) as "total_revenue",subscription_status from customer
 group by subscription_status;
---Q6.which 5 products has the highest percent of purchases with discount applied?
select item_purchased,round(100*sum(case when discount_applied='Yes'then 1 else 0 end)/count(*),2) as discount_rate from customer
 group by item_purchased
 order by discount_rate desc
 limit 5;
 ---Q7.segment customers into new,returning and loyal 
 ---based on their previous purchases and show count of each segment?
 with customer_type as (
select customer_id,previous_purchases,
CASE WHEN previous_purchases=1 then 'New'
     when previous_purchases between 2 and 10 then 'Returning'
	 else 'Loyal'
	 end as customer_segment
	 from customer
 )
 select customer_segment,count(*) as "number of customers" from customer_type
  group by customer_segment;
---Q8.what are the three top most purchased products within each category?
with item_count as (
select category,item_purchased,count(customer_id) as total_orders,
 ROW_NUMBER() over (partition by category
 order by count(customer_id) desc) as item_rank
 from customer
 group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders from item_count
 where item_rank>=3;
---Q9.Are customers who are repeated buyers (more then 5 previous purchases) are likely to subscribe?
select subscription_status,count(customer_id) as repeated_customers from customer
 where previous_purchases>5
 group by subscription_status
---Q10.what is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as total_revenue from customer
 group by age_group
 order by total_revenue desc;
 
 
 
